//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionAsistencia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int IdAsistencia { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime HoraFechaEntrada { get; set; }
        public Nullable<System.DateTime> HoraFechaSalida { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
