//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionAsistencia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int IdSolicitud { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> HoraFechaInicio { get; set; }
        public Nullable<System.DateTime> HoraFechaTermino { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> IdTipoSolicitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
