//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionAsistencia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turnos()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdTurno { get; set; }
        public string NombreTurno { get; set; }
        public Nullable<System.TimeSpan> HoraEntradaTurno { get; set; }
        public Nullable<System.TimeSpan> HoraSalidaTurno { get; set; }
        public Nullable<int> IdJornada { get; set; }
    
        public virtual Jornada Jornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
